TomarCampApp/TomarCampApp/Models/Funcionarios.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TomarCampApp.Models
{
    public class Funcionarios
    {

        public Funcionarios()
        {
            ListaDeObjetosDeConcretizacao = new HashSet<Concretizacao>();


        }

        public int ID { get; set; }


        public string Nome { get; set; }

        public string Foto { get; set; }



        public virtual ICollection<Concretizacao> ListaDeObjetosDeConcretizacao { get; set; }

        
    }
}

TomarCampApp/TomarCampApp/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TomarCampApp.Models;

namespace TomarCampApp.Controllers
{
    
    public class FuncionariosController : Controller
    {
        //Criar Var que representa a BD
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Funcionarios
        public ActionResult Index()
        {
            //procura a totalidade dos agentes na BD
            //Instrução feita em LINQ
            //SELECT * FROM Agentes ORDER BY nome
            var listaFuncionarios = db.Funcionarios.OrderBy(a => a.Nome).ToList();
            return View(listaFuncionarios);
        }

        /// <summary>
        /// Mostra os dados de um Agente
        /// </summary>
        /// <param name="id">identifica o Funcionario</param>
        /// <returns>devolve a View com os dados</returns>
        // GET: Funcionarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                //este erro ocorre porque o utilizador anda a fazer asneiras
                return RedirectToAction("Index");

            }
            // SELECT * FROM Agentes WHERE Id=id
            Funcionarios funcionarios = db.Funcionarios.Find(id);
            //O funcionario foi encontrado?
            if (funcionarios == null)
            {
                //O Funcionario não foi encontrado, porque o utilizador está a fazer asneira
                return RedirectToAction("Index");
            }
            return View(funcionarios);
        }
        [Authorize(Roles = "Admin")]
        // GET: Funcionarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Funcionarios/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.


        /// <summary>
        /// criação de um novo funcionário
        /// </summary>
        /// <param name="funcionarios">recolhe os dados do Nome do Funcionário</param>
        /// <param name="fotografia">representa a fotografia que identifica o Funcionário</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "ID,Nome")] Funcionarios funcionarios, HttpPostedFileBase fotografia)
        {

            /// precisamos de processar a fotografia
            /// 1º será que foi fornecido um ficheiro
            /// 2º será do tipo correto 
            /// 3º se for do tipo correto, guarda-se
            /// senão, atribui-se um ' avatar generico' ao utilizador

            //var auxiliar
            string caminho = "";
            bool haFicheiro = false;

            //há ficheiro?
            if (fotografia == null)
            {
                //não há ficheiro, atribui-se-lhe o avatar
                funcionarios.Foto = "nouser.png";
            }
            else
            {
                if (fotografia.ContentType == "image/jpeg" || fotografia.ContentType == "image/png")
                {
                    string extensao = Path.GetExtension(fotografia.FileName).ToLower();
                    Guid g;
                    g = Guid.NewGuid();
                    string nome = g.ToString() + extensao;

                    caminho = Path.Combine(Server.MapPath("~/imagens"), nome);
                    //atribuir ao agente o nome do ficheiro
                    funcionarios.Foto = nome;
                    //assinalar q ha foto
                    haFicheiro = true;
                }
            }


            if (ModelState.IsValid) //valida os dados fornecidos estão de acordo com as regras definidas no modelo 
            {
                try
                {
                    db.Funcionarios.Add(funcionarios);
                    db.SaveChanges();
                    //vou guardar o ficheiro no disco rigido
                    if (haFicheiro) fotografia.SaveAs(caminho);
                    //redireciona o utilizador para a página do INDEX
                    return RedirectToAction("Index");
                }catch (Exception)
                {
                    ModelState.AddModelError("", "Ocurreu um erro com a escrita dos dados do novo funcionário");
                }
            }

            return View(funcionarios);
        }

        [Authorize(Roles = "Admin, Func")]
        // GET: Funcionarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                //este erro ocorre porque o utilizador anda a fazer asneiras
                return RedirectToAction("Index");
            }
            Funcionarios funcionarios = db.Funcionarios.Find(id);
            if (funcionarios == null)
            {
                //o Funcionario nao foi encontrado porque o utilizador anda a fazer asneiras
                return RedirectToAction("Index");
            }
            return View(funcionarios);
        }

        // POST: Funcionarios/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Func")]
        public ActionResult Edit([Bind(Include = "ID,Nome,Foto")] Funcionarios funcionarios)
        {
            if (ModelState.IsValid)
            {
                db.Entry(funcionarios).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(funcionarios);
        }

        [Authorize(Roles = "Admin")]
        // GET: Funcionarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                //este erro ocorre porque o utilizador anda a fazer asneiras
                return RedirectToAction("Index");
            }
            Funcionarios funcionarios = db.Funcionarios.Find(id);
            if (funcionarios == null)
            {
                //o Funcionario nao foi encontrado porque o utilizador anda a fazer asneiras
                return RedirectToAction("Index");
            }
            // O Funcionario foi encontrado 
            // vou salvaguardar os dados para posterior validação
            // - guardar o ID do Funcionario num Cookie cifrado
            // - guardar o ID numa variavel de sessão
            
            Session["Funcionario"] = funcionarios.ID;
            //mostra na View os dados do Agente
            return View(funcionarios);
        }

        // POST: Funcionarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            if (id == null){

                //o utilizar está a tentar dar-me a volta ao código
                return RedirectToAction("Index");
            }
            //o ID não é null
            //será o ID o que eu espero?
            // vamos validar se o ID está correto
            if (id != (int)Session["Funcionario"])
            {
                // Caso o utilizador esteja a fazer asneiras
                return RedirectToAction("Index");
            }

            Funcionarios funcionarios = db.Funcionarios.Find(id);
            if(funcionarios == null)
            {
                //nao foi encontrado o agente
                return RedirectToAction("Index");
            }

            try
            {
                db.Funcionarios.Remove(funcionarios);
                db.SaveChanges();

            }
            catch (Exception)
            {
                //informar que houve um erro
                ModelState.AddModelError("", "Não é possivel remover o Funcionario " + funcionarios.Nome + ". Provalvemente possui concretizações associadas a ele");
                return View(funcionarios);
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TomarCampApp/TomarCampApp/Views/Funcionarios/Create.cshtml
@model TomarCampApp.Models.Funcionarios

@{
    ViewBag.Title = "Create";
}

<h2>Criar Funcionário</h2>


@using (Html.BeginForm("Create", "Funcionarios", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Funcionarios</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @* permite a introdução dos dados da fotografia do Agente *@
                <input type="file" accept=".jpg, .png" name="fotografia" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TomarCampApp/TomarCampApp/Views/Funcionarios/Delete.cshtml
@model TomarCampApp.Models.Funcionarios

@{
    ViewBag.Title = "Delete";
}

<h2>Apagar</h2>

<h3>Tem a certeza que quer apagar este funcionário?</h3>
<div>
    
    @*este 'helper' mostra as mensagens de erro que existem associadas ao Modelo*@
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            <img src="~/imagens/@Model.Foto" height="150" />
            @*@Html.DisplayFor(model => model.Foto)*@
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

TomarCampApp/TomarCampApp/Views/Funcionarios/Details.cshtml
@model TomarCampApp.Models.Funcionarios

@{
    ViewBag.Title = "Details";
}

<h2>Funcionario</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            <img src="~/imagens/@Model.Foto" height="150" />
            @*@Html.DisplayFor(model => model.Foto)*@
        </dd>

    </dl>
</div>
<p>
    @if (User.IsInRole("Func") || User.IsInRole("Admin"))
    {
        <text>
        @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
        </text>
    }
    @Html.ActionLink("Voltar", "Index")
    
</p>

TomarCampApp/TomarCampApp/Views/Funcionarios/Edit.cshtml
@model TomarCampApp.Models.Funcionarios

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Funcionario</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TomarCampApp/TomarCampApp/Views/Funcionarios/Index.cshtml
@model IEnumerable<TomarCampApp.Models.Funcionarios>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Funcionarios</h2>

<p>
    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Criar Novo Funcionario", "Create")
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            <img src="~/imagens/@item.Foto" height="50" />
            @*@Html.DisplayFor(modelItem => item.Foto)*@
        </td>
        <td>
            @Html.ActionLink("Detalhes", "Details", new { id = item.ID })

            @if (User.IsInRole("Func")||User.IsInRole("Admin"))
            {

                <text>
                |
                @Html.ActionLink("Editar", "Edit", new { id = item.ID }) 
                </text>
            }
            @if (User.IsInRole("Admin"))
            {
                <text>
                |
                @Html.ActionLink("Apagar", "Delete", new { id = item.ID })
                </text>
            }
            
        </td>
    </tr>
}

</table>