TomarCampApp/TomarCampApp/Models/Criancas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TomarCampApp.Models
{
    public class Criancas
    {

        public Criancas()
        {
            ListaDeObjetosDePlanoDeAtividades = new HashSet<PlanoDeAtividades>();


        }

        public int ID { get; set; }

        public string Nome { get; set; }

        public int Idade { get; set; }

        public string Doencas { get; set; }

        public string NumCC { get; set; }

        public string NIF { get; set; }


        [ForeignKey("Pai")]
        public int PaiFK { get; set; }
        public virtual Pais Pai { get; set; }


        public virtual ICollection<PlanoDeAtividades> ListaDeObjetosDePlanoDeAtividades { get; set; }
    }
}

TomarCampApp/TomarCampApp/Controllers/CriancasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TomarCampApp.Models;

namespace TomarCampApp.Controllers
{
    public class CriancasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Criancas
        public ActionResult Index()
        {
            
            
            ViewBag.mail = User.Identity.Name;
            var criancas = db.Criancas.Include(c => c.Pai);
            return View(criancas.ToList());
        }

        // GET: Criancas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Criancas criancas = db.Criancas.Find(id);
            if (criancas == null)
            {
                return HttpNotFound();
            }
            return View(criancas);
        }

        // GET: Criancas/Create/5
        public ActionResult Create(int ? id)
        {
            ViewBag.ListaObjetosDePai = db.Pais.OrderBy(p => p.Nome).ToList();
            ViewBag.ListaObjetosDePA = db.PlanoDeAtividades.OrderBy(pa => pa.Turno).ToList();
            return View();
        }

        // POST: Criancas/Create/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nome,Idade,Doencas,NumCC,NIF")] Criancas criancas, string[] opcoesEscolhidasDePA, string[] opcoesEscolhidasDePais)
        {

            /// avalia se o array com a lista das escolhas de objetos de PlanosDeAtividades associados ao objeto do tipo Criancas
            /// é nula, ou não.
            /// Só poderá avanção se NÃO for nula
            if (opcoesEscolhidasDePA == null)
            {
                ModelState.AddModelError("", "Necessita escolher pelo menos um PlanoDeAtividades para associar à criança.");
                // gerar a lista de objetos de PA que podem ser associados a Criança
                ViewBag.ListaObjetosDePA = db.PlanoDeAtividades.OrderBy(pa => pa.Turno).ToList();
                // devolver controlo à View
                return View(criancas);
            }

            
            List<PlanoDeAtividades> listaDeObjetosDePAEscolhidos = new List<PlanoDeAtividades>();
            foreach (string item in opcoesEscolhidasDePA)
            {
                
                PlanoDeAtividades pa = db.PlanoDeAtividades.Find(Convert.ToInt32(item));
                // adicioná-lo à lista
                listaDeObjetosDePAEscolhidos.Add(pa);
            }

            // adicionar a lista ao objeto de crianças
            criancas.ListaDeObjetosDePlanoDeAtividades = listaDeObjetosDePAEscolhidos;


            if (opcoesEscolhidasDePais == null)
            {
                ModelState.AddModelError("", "Necessita escolher o pai para associar à criança.");
                
                ViewBag.ListaObjetosDePai = db.Pais.OrderBy(p => p.Nome).ToList();
                // devolver controlo à View
                return View(criancas);
            }

            // criar um pai
            Pais pai =db.Pais.Find(Convert.ToInt32(opcoesEscolhidasDePais.First())) ;
            

            // adicionar o ID do pai ao PaiFK
            criancas.PaiFK = pai.ID;


            if (ModelState.IsValid)
            {
                db.Criancas.Add(criancas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            
            return View(criancas);
        }

        // GET: Criancas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Criancas criancas = db.Criancas.Find(id);
            if (criancas == null)
            {
                return HttpNotFound();
            }
            ViewBag.PaiFK = new SelectList(db.Pais, "ID", "Nome", criancas.PaiFK);
            return View(criancas);
        }

        // POST: Criancas/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,Idade,Doencas,NumCC,NIF,PaiFK")] Criancas criancas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(criancas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PaiFK = new SelectList(db.Pais, "ID", "Nome", criancas.PaiFK);
            return View(criancas);
        }

        // GET: Criancas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Criancas criancas = db.Criancas.Find(id);
            if (criancas == null)
            {
                return HttpNotFound();
            }
            return View(criancas);
        }

        // POST: Criancas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Criancas criancas = db.Criancas.Find(id);
            db.Criancas.Remove(criancas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TomarCampApp/TomarCampApp/Controllers/PlanoDeAtividadesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TomarCampApp.Models;

namespace TomarCampApp.Controllers
{
    public class PlanoDeAtividadesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PlanoDeAtividades
        public ActionResult Index()
        {
            return View(db.PlanoDeAtividades.ToList());
        }

        // GET: PlanoDeAtividades/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlanoDeAtividades planoDeAtividades = db.PlanoDeAtividades.Find(id);
            if (planoDeAtividades == null)
            {
                return HttpNotFound();
            }
            return View(planoDeAtividades);
        }

        // GET: PlanoDeAtividades/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlanoDeAtividades/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Turno,dataInicioPA,dataFimPA")] PlanoDeAtividades planoDeAtividades)
        {
            if (ModelState.IsValid)
            {
                db.PlanoDeAtividades.Add(planoDeAtividades);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(planoDeAtividades);
        }

        // GET: PlanoDeAtividades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlanoDeAtividades planoDeAtividades = db.PlanoDeAtividades.Find(id);
            if (planoDeAtividades == null)
            {
                return HttpNotFound();
            }
            return View(planoDeAtividades);
        }

        // POST: PlanoDeAtividades/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Turno,dataInicioPA,dataFimPA")] PlanoDeAtividades planoDeAtividades)
        {
            if (ModelState.IsValid)
            {
                db.Entry(planoDeAtividades).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(planoDeAtividades);
        }

        // GET: PlanoDeAtividades/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlanoDeAtividades planoDeAtividades = db.PlanoDeAtividades.Find(id);
            if (planoDeAtividades == null)
            {
                return HttpNotFound();
            }
            return View(planoDeAtividades);
        }

        // POST: PlanoDeAtividades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PlanoDeAtividades planoDeAtividades = db.PlanoDeAtividades.Find(id);
            db.PlanoDeAtividades.Remove(planoDeAtividades);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TomarCampApp/TomarCampApp/Views/Criancas/Create.cshtml
@model TomarCampApp.Models.Criancas

@{
    ViewBag.Title = "Create";
}

<h2>Adicionar Criança</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doencas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doencas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doencas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NIF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NIF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NIF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pai.Nome, "Pai", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ string selecionado = "";}
                @foreach (var item in ViewBag.ListaObjetosDePai)
                {
                    if (@item.Email == User.Identity.Name)
                    {
                    <input type="checkbox" name="opcoesEscolhidasDePais" value="@item.ID" @selecionado /> @item.Nome
                    <br />
                    }
                }

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ListaDeObjetosDePlanoDeAtividades.First().Turno, "Turno", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ string selected = "";}
                @foreach (var item in ViewBag.ListaObjetosDePA)
                {
                    <input type="checkbox" name="opcoesEscolhidasDePA" value="@item.ID" @selected /> @item.Turno
                    <br />
                }
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>

        </div>


        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
    </div>
}

TomarCampApp/TomarCampApp/Views/Criancas/Delete.cshtml
@model TomarCampApp.Models.Criancas

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Criancas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pai.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pai.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doencas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doencas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NIF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NIF)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TomarCampApp/TomarCampApp/Views/Criancas/Details.cshtml
@model TomarCampApp.Models.Criancas

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Criancas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pai.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pai.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doencas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doencas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NIF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NIF)
        </dd>

    </dl>


    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ListaDeObjetosDePlanoDeAtividades.First().Turno) |
                
            </th>
        </tr>
        @foreach (var item in Model.ListaDeObjetosDePlanoDeAtividades)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Turno, "Details", "PlanoDeAtividades", new { id = item.ID }, null)
                </td>
            </tr>
        }
    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TomarCampApp/TomarCampApp/Views/Criancas/Edit.cshtml
@model TomarCampApp.Models.Criancas

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Criancas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doencas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doencas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doencas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumCC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumCC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NIF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NIF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NIF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaiFK, "PaiFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PaiFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PaiFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TomarCampApp/TomarCampApp/Views/Criancas/Index.cshtml
@model IEnumerable<TomarCampApp.Models.Criancas>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Adicionar Criança", "Create")
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Idade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doencas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumCC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NIF)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.Pai.Email == ViewBag.mail)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Idade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Doencas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumCC)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NIF)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }
    }

</table>